# Visual clean
max_width = 120
use_small_heuristics = "Max"

# Imports
reorder_imports = true
group_imports = "StdExternalCrate"

# Inline style
match_block_trailing_comma = false

# Stable options only (safe for CI)
edition = "2021"
